DummyProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('form_app.urls')),
    path('reset/', include('django.contrib.auth.urls')),
]

form_app/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
app_name = 'form_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('save/', views.save, name='save'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.user_logout, name='logout'),
    path('librarian/', views.librarian, name='librarian'),
    path('uploaded/', views.uploaded, name='uploaded'),
    path('change_password/',views.change_password,name='password_change'),


]

form_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name= models.CharField(max_length=30)
    address = models.CharField(max_length = 100, blank=True,null=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True,null=True)
    resume = models.URLField(blank=True,null=True)

    def __str__(self):
        return self.name

class librarydue(models.Model):
    roll=models.CharField(primary_key=True,max_length=20)
    dues=models.IntegerField()

form_app/forms.py
from django import forms
from django.contrib.auth.models import User
from  . import  models



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = models.UserProfileInfo
        fields = ('name','address','profile_pic','resume')


class UploadForm(forms.Form):
    file=forms.FileField()

form_app/views.py
from django.shortcuts import render, redirect
from form_app.forms import UserProfileInfoForm, UserForm, UploadForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth.models import User
from form_app.models import UserProfileInfo, librarydue


def home(request):
    return render(request, 'form_app/home.html')


def register(request):
    profile_form = UserProfileInfoForm()
    user_form = UserForm()
    context = {'profile_form': profile_form, 'user_form': user_form}
    return render(request, 'form_app/register.html', context)


def save(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)

        if profile_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request['profile_pic']
            profile.save()

    return render(request, 'form_app/save.html')


def user_login(request):
    return render(request, 'form_app/login.html')


def profile(request):
    username = password = ''
    if request.method == 'POST':
        username = request.POST['id']
        password = request.POST['password']
        # print(username + ' password ' + password)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #
                a = User.objects.get(username=username)
                b = UserProfileInfo.objects.get(user=a.id)
                # print(b)
                context = {'user': a, 'profile': b}
                return render(request, 'form_app/profile.html', context)
            else:
                return HttpResponse('user is not active')
        else:
            return HttpResponse('Invalid details')
    else:
        return render(request, 'form_app/login.html')






@login_required
def user_logout(request):
    # a = User.objects.get(username=username)
    logout(request)
    return render(request, 'form_app/home.html')


# Create your views here.

def librarian(request):
    upload_form = UploadForm()
    context = {'upload': upload_form}
    return render(request, 'form_app/librarian.html', context)


def uploaded(request):
    import openpyxl

    if request.method == "POST":
        path = request.FILES['file']

    wb_obj = openpyxl.load_workbook(path)
    sheet_obj = wb_obj.active

    cell_obj = sheet_obj.cell(row=2, column=2)

    print(cell_obj.value)

    # book_resource = resources.modelresource_factory(model=librarydue)()
    # dataset = Dataset(['', 'static/library.ods'], headers=['roll', 'due'])
    # result = book_resource.import_data(dataset, dry_run=True)
    # print(result.has_errors())
    # result = book_resource.import_data(dataset, dry_run=False)
    # return render(request, 'form_app/home.html')
    # # if request.method == 'POST':
    # # person_resource = LibraryResource()
    # # dataset = Dataset()
    # # new_roll = request.FILES['file']
    # # dataset.load(open(request.FILES['file']).read())
    # # result = person_resource.import_data(dataset, dry_run=True)  # Test the data import
    # # if not result.has_errors():
    # #     person_resource.import_data(dataset, dry_run=False)  # Actually import now
    return render(request, 'form_app/home.html')


from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return render(request, 'form_app/home.html')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'form_app/change_password.html', {
        'form': form
    })

form_app/templates/change-password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
</body>
</html>

form_app/templates/form_app/change-password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
</body>
</html>

form_app/templates/form_app/change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
<!--<form  method="post" action="{%url 'form_app:pass_change'%}"  enctype="multipart/form-data">-->
    <!--{%csrf_token%}-->
    <!--<input type="password" name="old"><br>-->
    <!--<input type="password" name="new"><br>-->
    <!--<input type="submit">-->

<!--</form>-->
</body>
</html>

form_app/templates/form_app/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>

</body>
</html>

form_app/templates/form_app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h1>This is Home page</h1>
    <a href="{% url 'form_app:register' %}">Register Here<br></a>
    <a href="{% url 'form_app:login' %}">Login Here<br></a>
    <a href="{% url 'form_app:librarian' %}">Librarian<br></a>

</head>
<body>

</body>
</html>

form_app/templates/form_app/librarian.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h1>Upload library dues file</h1>


  <form action="{%url 'form_app:uploaded'%}" method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file">
    <button type="submit">Upload</button>
  </form>

</head>
<body>

</body>
</html>

form_app/templates/form_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Log in here</h1>
<form action="{% url 'form_app:profile'%}" method="POST">
    {% csrf_token %}
    <label> User's  Id </label>
    <input type="text" name="id"><br>
    <label>Password</label>
    <input type="password" name="password"><br>
    <input type="submit" value="LogIN" name="login"><br>
    <a href="/reset/password_reset">forget password</a>

</form>
</body>
</html>

form_app/templates/form_app/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Profile Of {{user.username}}</h1>
    <br><p>{{user.email}}</p>
    <br><p>{{profile.name}}</p>
<br><p>{{profile.address}}</p>
<p><a href="/change_password">change password</a></p>
<p><a href="{% url 'form_app:logout'%}">Logout</a></p>


</body>
</html>

form_app/templates/form_app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h2>Register Here</h2>

    <form action="{% url 'form_app:save' %}"method="POST" >
        {% csrf_token %}
        {{user_form.as_p}}
        {{ profile_form.as_p }}

        <input type="submit" value="register">

    </form>
</head>
<body>

</body>
</html>

form_app/templates/form_app/save.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h3>Your data is successfully saved !!</h3>
     <a href="{% url 'form_app:register' %}">Register More students <br></a>
    <a href="{% url 'form_app:home' %}">Exit</a>
</head>
<body>

</body>
</html>